In [2]:
import numpy as np
import pandas as pd
data = pd.read_csv("C:\VS Code Foders\EDA Project [Retail Dataset]\Datasets\messy_retail_dataset.csv")
df=data.copy()

<>:3: SyntaxWarning: invalid escape sequence '\V'
<>:3: SyntaxWarning: invalid escape sequence '\V'
C:\Users\kadam\AppData\Local\Temp\ipykernel_11796\3248791753.py:3: SyntaxWarning: invalid escape sequence '\V'
  data = pd.read_csv("C:\VS Code Foders\EDA Project [Retail Dataset]\Datasets\messy_retail_dataset.csv")

In [3]:
df.head()

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
0,10063,2022-10-23,1072,Canada,West,Printer,2,556,0.03,Express,Office,1112,372.051169
1,10498,2024-11-01,1063,Mexico,Central,Tablet,2,1851,0.33,EXPRESS,Electronics,3702,122.411691
2,10314,2024-05-16,1005,Japan,Central,Headphones,5,491,0.06,Same Day,Accessories,2455,413.755788
3,10109,2024-03-05,1025,Germany,North,Laptop,6,120,0.12,Same Day,Electronics,720,109.349998
4,10762,2022-11-14,1177,Germany,North,Printer,4,1504,0.22,Standard,Office,6016,873.037023

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       1040 non-null   int64
 1   OrderDate     1040 non-null   str
 2   CustomerID    1040 non-null   int64
 3   Country       1015 non-null   str
 4   Region        1013 non-null   str
 5   Product       1040 non-null   str
 6   Quantity      1040 non-null   int64
 7   UnitPrice     1040 non-null   int64
 8   Discount      1015 non-null   float64
 9   ShippingMode  1040 non-null   str
 10  Category      1040 non-null   str
 11  Sales         1040 non-null   int64
 12  Profit        1014 non-null   float64
dtypes: float64(2), int64(5), str(6)
memory usage: 105.8 KB

In [5]:
#Remove duplicates
df.drop_duplicates(inplace=True)

In [6]:
#sort by orderID
df.sort_values(by="OrderID",ignore_index=True,inplace=True)

In [7]:
#Converting into date formate
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [8]:
#Normalize the all text
df['ShippingMode']=df['ShippingMode'].str.title()
df["Product"]=df["Product"].apply(lambda x: x.title())

In [9]:
 #filled Country null values using Region column
for i in df['Region'].dropna().unique():
    a = df[df["Region"] == i]["Country"]
    df.loc[df['Region'] == i, "Country"] = df.loc[df['Region'] == i, "Country"].fillna(a.mode()[0])

In [10]:
 #filled Region null values using Country column
for i in df['Country'].dropna().unique():
    a = df[df["Country"] == i]["Region"]
    df.loc[df['Country']==i, "Region"] = df.loc[df['Country']==i, "Region"].fillna(a.mode()[0])

In [11]:
#delete row where country and region are null
df.dropna(subset=["Region"], axis=0,how='any',inplace=True)

In [12]:
df[["Discount","Profit"]].isna().mean()*100

Discount    2.502503
Profit      2.402402
dtype: float64

In [13]:
#Replacing null values with zero assuming there not given
df["Discount"] = df["Discount"].fillna(0)
#Replacing with median for avoid bias
df["Profit"] = df["Profit"].fillna(df["Profit"].median())

In [14]:
#Recreting Sales due to incorrect sales entries
df['Sales']=df['Quantity']*df['UnitPrice']

In [15]:
df[df["Quantity"]<0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, Country, Region, Product, Quantity, UnitPrice, Discount, ShippingMode, Category, Sales, Profit]
Index: []

In [16]:
df[(df["Discount"]>0.5) & (df["Discount"]<0)]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, Country, Region, Product, Quantity, UnitPrice, Discount, ShippingMode, Category, Sales, Profit]
Index: []

In [17]:
df.isnull().sum()

OrderID         0
OrderDate       0
CustomerID      0
Country         0
Region          0
Product         0
Quantity        0
UnitPrice       0
Discount        0
ShippingMode    0
Category        0
Sales           0
Profit          0
dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 999 entries, 0 to 999
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       999 non-null    int64
 1   OrderDate     999 non-null    datetime64[us]
 2   CustomerID    999 non-null    int64
 3   Country       999 non-null    str
 4   Region        999 non-null    str
 5   Product       999 non-null    str
 6   Quantity      999 non-null    int64
 7   UnitPrice     999 non-null    int64
 8   Discount      999 non-null    float64
 9   ShippingMode  999 non-null    str
 10  Category      999 non-null    str
 11  Sales         999 non-null    int64
 12  Profit        999 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(5), str(5)
memory usage: 109.3 KB

In [19]:
df.head()

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
0,10001,2024-05-10,1165,Germany,South,Headphones,9,1357,0.14,Standard,Accessories,12213,2548.376394
1,10002,2024-12-31,1033,UK,North,Tablet,4,51,0.17,Same Day,Electronics,204,6.142379
2,10003,2024-11-10,1016,Mexico,North,Smartwatch,7,306,0.31,Standard,Electronics,2142,324.025711
3,10004,2022-05-02,1164,Japan,West,Keyboard,6,613,0.19,Express,Accessories,3678,439.805380
4,10005,2023-04-12,1152,Japan,East,Laptop,2,1086,0.32,Express,Electronics,2172,-470.616919

In [20]:
df.describe()

,OrderID,OrderDate,CustomerID,Quantity,UnitPrice,Discount,Sales,Profit
count,999.000000,999,999.00000,999.000000,999.000000,999.000000,999.000000,999.000000
mean,10500.108108,2023-07-18 20:28:06.486486,1097.64965,5.041041,978.772773,0.192793,4876.538539,543.644178
min,10001.000000,2022-01-01 00:00:00,1000.00000,1.000000,23.000000,0.000000,30.000000,-3283.986623
25%,10250.500000,2022-09-26 12:00:00,1046.00000,3.000000,516.000000,0.090000,1693.500000,-7.149967
50%,10500.000000,2023-08-16 00:00:00,1097.00000,5.000000,976.000000,0.190000,3810.000000,238.404736
75%,10749.500000,2024-04-16 00:00:00,1149.00000,7.000000,1422.000000,0.290000,7146.500000,841.982692
max,11000.000000,2024-12-31 00:00:00,1199.00000,9.000000,1997.000000,0.400000,17829.000000,7063.491230
std,288.697969,NaN,58.47951,2.543670,554.453595,0.117664,3907.046888,1178.409342

In [21]:
df.sort_values("Profit").head(10)

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
867,10868,2022-07-21,1002,Australia,North,Tablet,8,1716,0.35,Express,Electronics,13728,-3283.986623
752,10753,2022-09-18,1180,UK,South,Laptop,7,1653,0.40,Express,Electronics,11571,-3195.433632
481,10482,2024-07-17,1014,France,Central,Smartwatch,9,1936,0.34,Standard,Electronics,17424,-2873.686882
987,10988,2022-08-25,1146,Germany,East,Laptop,7,1981,0.38,Express,Electronics,13867,-2680.713485
505,10506,2024-10-28,1165,Brazil,East,Smartwatch,8,1318,0.35,Express,Electronics,10544,-2487.078564
371,10372,2022-06-09,1062,India,East,Mobile,8,1352,0.33,Same Day,Electronics,10816,-2441.027059
788,10789,2024-09-19,1118,India,West,Smartwatch,8,1458,0.33,Same Day,Electronics,11664,-2117.627874
564,10565,2023-05-03,1071,India,Central,Keyboard,9,1502,0.29,Standard,Accessories,13518,-2106.734093
720,10721,2023-04-13,1120,India,West,Smartwatch,8,1974,0.31,Express,Electronics,15792,-2063.335911
900,10901,2023-04-21,1024,Canada,East,Mouse,8,1560,0.37,Standard,Accessories,12480,-2035.355290

#Conclusion: The majority of loss-making transactions belong to the Electronics category,
#where higher discount rates (around 30–40%) significantly reduce profitability.

In [22]:
#cleaned dataset
df.to_csv("C:\VS Code Foders\EDA Project [Retail Dataset]\Cleaned_retail_dataset.csv",index=False)

<>:2: SyntaxWarning: invalid escape sequence '\V'
<>:2: SyntaxWarning: invalid escape sequence '\V'
C:\Users\kadam\AppData\Local\Temp\ipykernel_11796\1832484583.py:2: SyntaxWarning: invalid escape sequence '\V'
  df.to_csv("C:\VS Code Foders\EDA Project [Retail Dataset]\Cleaned_retail_dataset.csv",index=False)