In [15]:
import numpy as np
import pandas as pd
data = pd.read_csv("messy_retail_dataset.csv")
df=data.copy()

In [16]:
df.head()

,OrderID,OrderDate,CustomerID,Country,Region,Product,Quantity,UnitPrice,Discount,ShippingMode,Category,Sales,Profit
0,10063,2022-10-23,1072,Canada,West,Printer,2,556,0.03,Express,Office,1112,372.051169
1,10498,2024-11-01,1063,Mexico,Central,Tablet,2,1851,0.33,EXPRESS,Electronics,3702,122.411691
2,10314,2024-05-16,1005,Japan,Central,Headphones,5,491,0.06,Same Day,Accessories,2455,413.755788
3,10109,2024-03-05,1025,Germany,North,Laptop,6,120,0.12,Same Day,Electronics,720,109.349998
4,10762,2022-11-14,1177,Germany,North,Printer,4,1504,0.22,Standard,Office,6016,873.037023

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       1040 non-null   int64
 1   OrderDate     1040 non-null   str
 2   CustomerID    1040 non-null   int64
 3   Country       1015 non-null   str
 4   Region        1013 non-null   str
 5   Product       1040 non-null   str
 6   Quantity      1040 non-null   int64
 7   UnitPrice     1040 non-null   int64
 8   Discount      1015 non-null   float64
 9   ShippingMode  1040 non-null   str
 10  Category      1040 non-null   str
 11  Sales         1040 non-null   int64
 12  Profit        1014 non-null   float64
dtypes: float64(2), int64(5), str(6)
memory usage: 105.8 KB

In [18]:
#Remove duplicates
df.drop_duplicates(inplace=True)

In [19]:
#sort by orderID
df.sort_values(by="OrderID",ignore_index=True,inplace=True)

In [20]:
#Converting into date formate
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [21]:
#Normalize the all text
df['ShippingMode']=df['ShippingMode'].str.title()
df["Product"]=df["Product"].apply(lambda x: x.title())

In [22]:
 #filled Country null values using Region column
for i in df['Region'].dropna().unique():
    a = df[df["Region"] == i]["Country"]
    df.loc[df['Region'] == i, "Country"] = df.loc[df['Region'] == i, "Country"].fillna(a.mode()[0])

In [23]:
 #filled Region null values using Country column
for i in df['Country'].dropna().unique():
    a = df[df["Country"] == i]["Region"]
    df.loc[df['Country']==i, "Region"] = df.loc[df['Country']==i, "Region"].fillna(a.mode()[0])

In [24]:
#delete row where country and region are null
df.dropna(subset=["Region"], axis=0,how='any',inplace=True)

In [ ]:
#Replacing null values with zero assuming there not given
df["Discount"] = df["Discount"].fillna(0)
#Replacing with median for avoid bias
df["Profit"] = df["Profit"].fillna(df["Profit"].median())

Discount    2.502503
Profit      2.402402
dtype: float64

In [53]:
#Replacing null values into zero assuming No prfit and No Discount
df["Discount"].fillna(0, inplace=True)
df["Profit"].fillna(0, inplace=True)

C:\Users\kadam\AppData\Local\Temp\ipykernel_9568\777340225.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Discount"].fillna(0, inplace=True)
C:\Users\kadam\AppData\Local\Temp\ipykernel_9568\777340225.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Profit"].fillna(0, inplace=True)

0      2548.376394
1         6.142379
2       324.025711
3       439.805380
4      -470.616919
          ...
995    1357.283178
996    3803.584875
997    2055.151260
998    -249.635788
999    -180.228113
Name: Profit, Length: 999, dtype: float64

In [26]:
df['Sales']=df['Quantity']*df['UnitPrice']
df['Sales'].count()

np.int64(999)

In [27]:
df[df["Quantity"]<0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, Country, Region, Product, Quantity, UnitPrice, Discount, ShippingMode, Category, Sales, Profit]
Index: []

In [31]:
df[(df["Discount"]>0.5) & (df["Discount"]<0)]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, Country, Region, Product, Quantity, UnitPrice, Discount, ShippingMode, Category, Sales, Profit]
Index: []

In [55]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
Country          0
Region           0
Product          0
Quantity         0
UnitPrice        0
Discount        25
ShippingMode     0
Category         0
Sales            0
Profit          24
dtype: int64